#!/bin/bash

# Auto-Build Environment Setup for SyncthingTemplar
# Generated by Planner Agent
# Spec: 001-project-setup

set -e

echo "========================================"
echo "SyncthingTemplar Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Project root (relative to spec directory)
PROJECT_ROOT="../../.."

# Navigate to project root
cd "$(dirname "$0")/$PROJECT_ROOT"

echo ""
echo "Project root: $(pwd)"
echo ""

# ============================================
# PREREQUISITES CHECK
# ============================================

echo "Checking prerequisites..."

# Check for .NET SDK
if ! command -v dotnet &> /dev/null; then
    echo -e "${RED}.NET SDK not found. Please install .NET 9 SDK.${NC}"
    exit 1
fi

DOTNET_VERSION=$(dotnet --version)
echo -e "${GREEN}.NET SDK found: $DOTNET_VERSION${NC}"

# Verify .NET 9.x
if [[ ! "$DOTNET_VERSION" =~ ^9\. ]]; then
    echo -e "${YELLOW}Warning: Expected .NET 9.x, found $DOTNET_VERSION${NC}"
fi

# ============================================
# BUILD AND RUN
# ============================================

echo ""
echo "========================================"
echo "Building Solution"
echo "========================================"

# Build the solution
if [ -f "SyncthingTemplar.sln" ]; then
    dotnet build SyncthingTemplar.sln
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}Build succeeded${NC}"
    else
        echo -e "${RED}Build failed${NC}"
        exit 1
    fi
else
    echo -e "${YELLOW}Solution file not found - project needs to be created first${NC}"
fi

echo ""
echo "========================================"
echo "Starting Development Server"
echo "========================================"

# Start the application
if [ -d "src/SyncthingTemplar" ]; then
    echo "Starting Blazor Server application..."
    echo "Application will be available at:"
    echo "  HTTP:  http://localhost:5000"
    echo "  HTTPS: https://localhost:5001"
    echo ""
    echo "Press Ctrl+C to stop the server"
    echo ""

    cd src/SyncthingTemplar
    dotnet run
else
    echo -e "${YELLOW}Project directory not found - project needs to be created first${NC}"
fi
