#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Dark Mode Theme Persistence and System Sync

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# RESTORE DEPENDENCIES
# ============================================

echo -e "${YELLOW}Restoring .NET dependencies...${NC}"
dotnet restore

# ============================================
# START BLAZOR SERVER APP
# ============================================

echo -e "${YELLOW}Starting SyncthingTemplar Blazor Server...${NC}"

# Run in watch mode for hot reload during development
cd src/SyncthingTemplar && dotnet watch run &

# Wait for HTTPS port to be ready
wait_for_service 5134 "SyncthingTemplar (HTTPS)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  SyncthingTemplar UI (HTTPS): https://localhost:5134"
echo "  SyncthingTemplar UI (HTTP):  http://localhost:5135"
echo ""
echo "Feature: Dark Mode Theme Persistence and System Sync"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for user to terminate
wait
