#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Node Configuration Management
# Spec: 003-node-configuration-management

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# ENSURE DIRECTORIES
# ============================================

echo ""
echo "Creating required directories..."

# Create Data Protection API keys directory
mkdir -p ./keys
echo -e "${GREEN}Created ./keys directory for Data Protection API${NC}"

# Create Dialogs directory if it doesn't exist
mkdir -p ./src/SyncthingTemplar/Components/Dialogs
echo -e "${GREEN}Created ./src/SyncthingTemplar/Components/Dialogs directory${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting SyncthingTemplar Blazor Server..."

# Navigate to project directory and start with hot reload
cd ./src/SyncthingTemplar
dotnet watch run &

# Wait for service to be ready
wait_for_service 5000 "SyncthingTemplar"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  SyncthingTemplar: http://localhost:5000"
echo ""
echo "Key Pages:"
echo "  - Home:    http://localhost:5000/"
echo "  - Servers: http://localhost:5000/servers"
echo ""
echo "Development:"
echo "  - Hot reload enabled (dotnet watch)"
echo "  - Press Ctrl+C to stop all services"
echo ""
